/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Frame;

import Controller.ProductController;
import Controller.TransactionController;
import static Frame.ProductFrame.id;
import static Frame.ProductFrame.name;
import Helper.Helper;
import Model.ProductModel;
import Model.TransactionModel;
import java.sql.ResultSet;
import java.text.ParseException;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author hp
 */
public class TransactionFrame extends javax.swing.JFrame {

    TransactionModel transModel = new TransactionModel();
    ProductModel productModel = new ProductModel();
    
    Helper helper = new Helper();
    SpinnerNumberModel spinner = new SpinnerNumberModel();
    ProductController controllerProduct = new ProductController();
    TransactionController controllerTrans = new TransactionController();
    DefaultTableModel defaultModel;
    ResultSet rs;
    ResultSet rs1;
    String product_id;
    String transaction_id;

    public TransactionFrame() {
        initComponents();

        label_id.setText(ProductFrame.id);
        label_name.setText(ProductFrame.name);

        this.clear();
    }

    public void getAllDataProduct() {
        this.rs = controllerProduct.get();
        this.loadTableProduct(this.rs);
    }
    public void getAllDataTrans() {
        this.rs1 = controllerTrans.get();
        this.loadTableTrans(this.rs1);
    }

    public void clear() {
        this.getAllDataProduct();
        this.getAllDataTrans();
        tf_id.setText("");
        tf_merk.setText("");
        tf_series.setText("");
        spn_totalorder.setValue(0);
        tf_Total.setText("");
        tf_price.setText("");
        tf_stock.setText("");
        tf_customer.setText("");
        tf_customer.setEnabled(false);
        dp_date.setDate(null);
        btn_save.setEnabled(false);
        dp_date.setEnabled(false);
        spn_totalorder.setEnabled(false);
        btn_updatetrans.setEnabled(false);
        btn_delete.setEnabled(false);

    }


    public void loadTableProduct(ResultSet rs) {
        tb_product.setModel(DbUtils.resultSetToTableModel(rs));
    }

    public void loadTableTrans(ResultSet rs1) {
        tb_transaction.setModel(DbUtils.resultSetToTableModel(rs1));
    }

    private void searchProduct (String type, String query) {
        try {
            if(query.isEmpty()) {
                this.rs = controllerProduct.get();
            } else if (type.equals("id") && !query.isEmpty()) {
                this.rs = controllerProduct.showById(query);
            } else if (type.equals("series") && !query.isEmpty()) {
                this.rs = controllerProduct.showBySeries(query);
            }
            
            this.loadTableProduct(this.rs);
        }catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
}

    private void searchTrans (String type, String query) {
        try {
            if(query.isEmpty()) {
                this.rs1 = controllerTrans.get();
            } else if (type.equals("id") && !query.isEmpty()) {
                this.rs1 = controllerTrans.showById(query);
            } else if (type.equals("transaction_date") && !query.isEmpty()) {
                this.rs1 = controllerTrans.showByDate(query);
            }
            
            this.loadTableTrans(this.rs1);
        }catch(Exception ex) {
            System.out.println(ex.getMessage());
        }
}

    /**
     * Creates new form TransactionFrame
     */

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        label_name = new javax.swing.JLabel();
        label_id = new javax.swing.JLabel();
        label_idtitle = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_product = new javax.swing.JTable();
        btn_refreshProduct = new javax.swing.JButton();
        tf_findProduct = new javax.swing.JTextField();
        btn_searchnameProduct = new javax.swing.JButton();
        btn_searchidProduct = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btn_inputproduct = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_id = new javax.swing.JTextField();
        tf_price = new javax.swing.JTextField();
        tf_series = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        tf_merk = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        tf_stock = new javax.swing.JTextField();
        spn_totalorder = new javax.swing.JSpinner();
        btn_reset = new javax.swing.JButton();
        dp_date = new org.jdesktop.swingx.JXDatePicker();
        jLabel25 = new javax.swing.JLabel();
        tf_customer = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_transaction = new javax.swing.JTable();
        btn_refreshTransaction = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        tf_findTransaction = new javax.swing.JTextField();
        btn_searchnameTransaction = new javax.swing.JButton();
        btn_searchidTransaction = new javax.swing.JButton();
        tf_Total = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        btn_logout = new javax.swing.JButton();
        btn_updatetrans = new javax.swing.JButton();
        btn_delete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 102, 51));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("SMARTPHONE STORE");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, -1, -1));

        label_name.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        label_name.setForeground(new java.awt.Color(255, 255, 255));
        label_name.setText("ADMIN : ");
        jPanel2.add(label_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 270, -1));

        label_id.setFont(new java.awt.Font("Baskerville Old Face", 1, 48)); // NOI18N
        label_id.setForeground(new java.awt.Color(255, 255, 255));
        label_id.setText("0");
        jPanel2.add(label_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(1200, 30, 30, 50));

        label_idtitle.setFont(new java.awt.Font("Baskerville Old Face", 1, 14)); // NOI18N
        label_idtitle.setForeground(new java.awt.Color(255, 255, 255));
        label_idtitle.setText("ID ADMIN : ");
        jPanel2.add(label_idtitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1170, 10, -1, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1330, 80));

        jPanel3.setBackground(new java.awt.Color(0, 102, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_product.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_product.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_productMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tb_product);

        jPanel3.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 590, 170));

        btn_refreshProduct.setBackground(new java.awt.Color(0, 0, 0));
        btn_refreshProduct.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_refreshProduct.setForeground(new java.awt.Color(255, 255, 255));
        btn_refreshProduct.setText("Refresh");
        btn_refreshProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshProductActionPerformed(evt);
            }
        });
        jPanel3.add(btn_refreshProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 40, 120, -1));
        jPanel3.add(tf_findProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, 30));

        btn_searchnameProduct.setBackground(new java.awt.Color(0, 0, 0));
        btn_searchnameProduct.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_searchnameProduct.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchnameProduct.setText("Search by series");
        btn_searchnameProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchnameProductActionPerformed(evt);
            }
        });
        jPanel3.add(btn_searchnameProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, 160, -1));

        btn_searchidProduct.setBackground(new java.awt.Color(0, 0, 0));
        btn_searchidProduct.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_searchidProduct.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchidProduct.setText("Search by id");
        btn_searchidProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchidProductActionPerformed(evt);
            }
        });
        jPanel3.add(btn_searchidProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 120, -1));

        jLabel6.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Find Product");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btn_inputproduct.setBackground(new java.awt.Color(0, 0, 0));
        btn_inputproduct.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_inputproduct.setForeground(new java.awt.Color(255, 255, 255));
        btn_inputproduct.setText("Input Product");
        btn_inputproduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_inputproductActionPerformed(evt);
            }
        });
        jPanel3.add(btn_inputproduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 10, 420, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 610, 250));

        jPanel4.setBackground(new java.awt.Color(0, 102, 51));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel19.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Id Product");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel20.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Merk");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jLabel21.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Price");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, -1, -1));

        jLabel22.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Transaction_date");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, -1, -1));

        jLabel12.setFont(new java.awt.Font("Baskerville Old Face", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Transaction");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, -1, -1));

        tf_id.setBackground(new java.awt.Color(153, 153, 153));
        tf_id.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_id.setEnabled(false);
        jPanel4.add(tf_id, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 150, 30));

        tf_price.setBackground(new java.awt.Color(153, 153, 153));
        tf_price.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_price.setEnabled(false);
        jPanel4.add(tf_price, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, 150, 30));

        tf_series.setBackground(new java.awt.Color(153, 153, 153));
        tf_series.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_series.setEnabled(false);
        jPanel4.add(tf_series, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 150, 30));

        jLabel23.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("series");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        tf_merk.setBackground(new java.awt.Color(153, 153, 153));
        tf_merk.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_merk.setEnabled(false);
        jPanel4.add(tf_merk, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 150, 30));

        jLabel24.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Customer_name");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 130, -1, -1));

        tf_stock.setBackground(new java.awt.Color(153, 153, 153));
        tf_stock.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        tf_stock.setEnabled(false);
        jPanel4.add(tf_stock, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 80, 160, 30));

        spn_totalorder.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                spn_totalorderStateChanged(evt);
            }
        });
        jPanel4.add(spn_totalorder, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 70, 30));

        btn_reset.setBackground(new java.awt.Color(0, 0, 0));
        btn_reset.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_reset.setForeground(new java.awt.Color(255, 255, 255));
        btn_reset.setText("Reset");
        btn_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_resetActionPerformed(evt);
            }
        });
        jPanel4.add(btn_reset, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 120, 30));
        jPanel4.add(dp_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 140, 30));

        jLabel25.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Total Order");
        jPanel4.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 170, -1, -1));

        tf_customer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jPanel4.add(tf_customer, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 120, 160, 30));

        jLabel26.setFont(new java.awt.Font("Baskerville Old Face", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Stock");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, 710, 250));

        jPanel6.setBackground(new java.awt.Color(0, 102, 51));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_transaction.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tb_transaction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_transactionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tb_transactionMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tb_transaction);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 1180, 170));

        btn_refreshTransaction.setBackground(new java.awt.Color(0, 0, 0));
        btn_refreshTransaction.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_refreshTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btn_refreshTransaction.setText("Refresh");
        btn_refreshTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_refreshTransactionActionPerformed(evt);
            }
        });
        jPanel6.add(btn_refreshTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 120, 30));

        jLabel5.setFont(new java.awt.Font("Baskerville Old Face", 0, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Find Transaction");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, 20));
        jPanel6.add(tf_findTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 200, 30));

        btn_searchnameTransaction.setBackground(new java.awt.Color(0, 0, 0));
        btn_searchnameTransaction.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_searchnameTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchnameTransaction.setText("Search by date");
        btn_searchnameTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchnameTransactionActionPerformed(evt);
            }
        });
        jPanel6.add(btn_searchnameTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 40, 160, 30));

        btn_searchidTransaction.setBackground(new java.awt.Color(0, 0, 0));
        btn_searchidTransaction.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_searchidTransaction.setForeground(new java.awt.Color(255, 255, 255));
        btn_searchidTransaction.setText("Search by id");
        btn_searchidTransaction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchidTransactionActionPerformed(evt);
            }
        });
        jPanel6.add(btn_searchidTransaction, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 120, 30));

        tf_Total.setEditable(false);
        tf_Total.setBackground(new java.awt.Color(255, 102, 102));
        tf_Total.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tf_Total.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tf_Total.setText("0");
        tf_Total.setEnabled(false);
        jPanel6.add(tf_Total, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 340, 70));

        jLabel18.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Total Amount");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, 20));

        btn_save.setBackground(new java.awt.Color(255, 255, 255));
        btn_save.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btn_save.setText("SAVE");
        btn_save.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_saveMouseClicked(evt);
            }
        });
        jPanel6.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 270, 250, 30));

        btn_logout.setBackground(new java.awt.Color(0, 0, 0));
        btn_logout.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_logout.setForeground(new java.awt.Color(255, 255, 255));
        btn_logout.setText("LOG OUT");
        btn_logout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btn_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_logoutMouseClicked(evt);
            }
        });
        jPanel6.add(btn_logout, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, 320, 40));

        btn_updatetrans.setBackground(new java.awt.Color(255, 255, 255));
        btn_updatetrans.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_updatetrans.setText("Update");
        btn_updatetrans.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_updatetransActionPerformed(evt);
            }
        });
        jPanel6.add(btn_updatetrans, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 310, 120, 30));

        btn_delete.setBackground(new java.awt.Color(255, 255, 255));
        btn_delete.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        btn_delete.setText("Delete");
        btn_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_deleteActionPerformed(evt);
            }
        });
        jPanel6.add(btn_delete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 310, 120, 30));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 1330, 360));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_refreshProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshProductActionPerformed
        // TODO add your handling code here:
            this.getAllDataProduct();
            tf_findProduct.setText("");
    }//GEN-LAST:event_btn_refreshProductActionPerformed

    private void btn_refreshTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_refreshTransactionActionPerformed
        // TODO add your handling code here:
            this.getAllDataTrans();
            tf_findTransaction.setText("");
    }//GEN-LAST:event_btn_refreshTransactionActionPerformed

    private void btn_searchnameProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchnameProductActionPerformed
        // TODO add your handling code here:
        this.searchProduct("series", tf_findProduct.getText());
    }//GEN-LAST:event_btn_searchnameProductActionPerformed

    private void btn_searchidProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchidProductActionPerformed
        // TODO add your handling code here:
        this.searchProduct("id", tf_findProduct.getText());
    }//GEN-LAST:event_btn_searchidProductActionPerformed

    private void btn_searchnameTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchnameTransactionActionPerformed
        // TODO add your handling code here:
        this.searchTrans("transaction_date", tf_findTransaction.getText());
    }//GEN-LAST:event_btn_searchnameTransactionActionPerformed

    private void btn_searchidTransactionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchidTransactionActionPerformed
        // TODO add your handling code here:
        this.searchTrans("id", tf_findTransaction.getText());
    }//GEN-LAST:event_btn_searchidTransactionActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.getAllDataProduct();
        this.getAllDataTrans();
        this.clear();
    }//GEN-LAST:event_formWindowOpened

    private void btn_inputproductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_inputproductActionPerformed
        // TODO add your handling code here
        id = label_id.getText();
        name = label_name.getText();

        ProductFrame frame = new ProductFrame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_inputproductActionPerformed

    private void tb_transactionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_transactionMouseClicked
        // TODO add your handling code here:
        try{        
            // TODO add your handling code here:
            String id_trans = helper.getValueRows(tb_transaction, 0);
            String id_product = helper.getValueRows(tb_transaction, 3);
            String merk = helper.getValueRows(tb_transaction, 4);
            String series = helper.getValueRows(tb_transaction, 5);
            String price = helper.getValueRows(tb_transaction,6);
            String total_order = helper.getValueRows(tb_transaction, 7);
            String stock = helper.getValueRows(tb_transaction, 8);
            String customer_name = helper.getValueRows(tb_transaction, 10);
            String transaction_date = helper.getValueRows(tb_transaction, 11);



            Date date = new Date(helper.parseStringToDatePickerFormat(transaction_date));
            int Total_Order = Integer.parseInt(total_order);
            int Stock = Integer.parseInt(stock);
            int OldStock = (Total_Order + Stock);

            this.transaction_id = id_trans;

            btn_updatetrans.setEnabled(true);
            btn_delete.setEnabled(true);
            dp_date.setEnabled(true);
            spn_totalorder.setEnabled(true);
            tf_customer.setEnabled(true);
            

            tf_id.setText(id_product);
            tf_merk.setText(merk);
            tf_series.setText(series);
            tf_price.setText(price);
            tf_stock.setText(String.valueOf(OldStock));
            tf_customer.setText(customer_name);
            dp_date.setDate(date);
            spn_totalorder.setValue(Total_Order);

           this.getAllDataProduct();


        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }



    }//GEN-LAST:event_tb_transactionMouseClicked

    private void tb_productMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_productMouseClicked
        // TODO add your handling code here:
        try {

        String id = helper.getValueRows(tb_product, 0);
        String merk = helper.getValueRows(tb_product, 1);
        String series = helper.getValueRows(tb_product, 2);
        String price = helper.getValueRows(tb_product, 3);
        String stock = helper.getValueRows(tb_product, 4);


        tf_id.setText(id);
        tf_merk.setText(merk);
        tf_series.setText(series);
        tf_price.setText(price);
        tf_stock.setText(stock);
        spn_totalorder.setValue(0);

        dp_date.setEnabled(true);
        spn_totalorder.setEnabled(true);
        tf_customer.setEnabled(true);

        

        int Stock = Integer.parseInt(tf_stock.getText());

         if(Stock == 0){
            JOptionPane.showMessageDialog(null, "out of stock!");
            this.clear();
        }

        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_tb_productMouseClicked

    private void spn_totalorderStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_spn_totalorderStateChanged
        // TODO add your handling code here:
        Integer stock, price, totalOrder, totalAmount;
        stock = Integer.parseInt(tf_stock.getText());
        price = Integer.parseInt(tf_price.getText());
        totalOrder = (Integer) spn_totalorder.getValue();

        spinner.setMinimum(0);
        spinner.setMaximum(stock + 1);
        spn_totalorder.setModel(spinner);

        totalAmount = 0;

        if (stock < totalOrder) {
             spn_totalorder.setValue(stock);
            JOptionPane.showMessageDialog(null, "Sorry, not enough stock");
         }

        else if (totalOrder == 0)
        {
            btn_save.setEnabled(false);
            tf_Total.setText(String.valueOf(totalAmount));
        }

        else
        {
            totalAmount = (price * totalOrder);
            btn_save.setEnabled(true);
            tf_Total.setText(String.valueOf(totalAmount));
        }
    }//GEN-LAST:event_spn_totalorderStateChanged

    private void btn_saveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_saveMouseClicked
        // TODO add your handling code here:
        try {


            String id_employee = label_id.getText();
            String id_product = tf_id.getText();
            String total_order = spn_totalorder.getValue().toString();
            String total_amount = tf_Total.getText();
            String customer_name = tf_customer.getText();
            Date date = dp_date.getDate();

            transModel.setId_employee(id_employee);
            transModel.setId_product(id_product);
            transModel.setTotal_amount(total_amount);
            transModel.setCustomer_name(customer_name);
            transModel.setTotal_order(total_order);
            transModel.setTransaction_date(date);
 
            String msg = "Failed to add data!";

            Boolean result = controllerTrans.create(transModel);

            if(result){

                    Integer stock, total_orderr, remaining_stock;
                    String product_id;

                    product_id = tf_id.getText(); 
                    stock = Integer.parseInt(tf_stock.getText());
                    total_orderr =(Integer) spn_totalorder.getValue();
                    remaining_stock = (stock - total_orderr);
                    productModel.setRemaining_stock(String.valueOf(remaining_stock));

                    controllerProduct.update_stock(product_id, productModel);
                    msg = "Successfully added data";

                    this.clear();
                    }

            JOptionPane.showMessageDialog(null, msg);
            this.getAllDataTrans();
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                    } 
    }//GEN-LAST:event_btn_saveMouseClicked

    private void btn_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_logoutMouseClicked
        // TODO add your handling code here:
        LoginFrame frame = new LoginFrame();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_logoutMouseClicked

    private void btn_updatetransActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_updatetransActionPerformed
        // TODO add your handling code here:
        try{
            String id_employee = label_id.getText();
            String id_product = tf_id.getText();
            String total_order = spn_totalorder.getValue().toString();
            String total_amount = tf_Total.getText();
            String customer_name = tf_customer.getText();
            Date date = dp_date.getDate();

            transModel.setId_employee(id_employee);
            transModel.setId_product(id_product);
            transModel.setTotal_amount(total_amount);
            transModel.setCustomer_name(customer_name);
            transModel.setTotal_order(total_order);
            transModel.setTransaction_date(date);

            Boolean result = controllerTrans.update(this.transaction_id, transModel);

            String msg = "Failed to change data!";
            if(result) {

            Integer stock, total_orderr, remaining_stock;
            String product_id;
            product_id = tf_id.getText(); 
            stock = Integer.parseInt(tf_stock.getText());
            total_orderr =(Integer) spn_totalorder.getValue();
            remaining_stock = (stock - total_orderr);
            productModel.setRemaining_stock(String.valueOf(remaining_stock));
            controllerProduct.update_stock(product_id, productModel);

                msg = "Successfully changed data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            this.clear();
            this.getAllDataTrans();
            
        } catch (ParseException ex) {
            System.out.println(ex.getMessage());
        }

    }//GEN-LAST:event_btn_updatetransActionPerformed

    private void btn_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_deleteActionPerformed
        // TODO add your handling code here:
       try {
            
            Boolean result = controllerTrans.delete(this.transaction_id);
            
            String msg = "Failed to delete data!";
            if(result) {

            Integer stock, remaining_stock;
            String product_id;
            product_id = tf_id.getText(); 
            stock = Integer.parseInt(tf_stock.getText());
            remaining_stock = (stock);
            productModel.setRemaining_stock(String.valueOf(remaining_stock));
            controllerProduct.update_stock(product_id, productModel);

                msg = "Successfully delete data";
            }
            
            JOptionPane.showMessageDialog(null, msg);
            
            this.clear();
            this.getAllDataTrans();
            
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btn_deleteActionPerformed

    private void btn_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_resetActionPerformed
        // TODO add your handling code here:
        this.clear();
    }//GEN-LAST:event_btn_resetActionPerformed

    private void tb_transactionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_transactionMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tb_transactionMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TransactionFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TransactionFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_delete;
    private javax.swing.JButton btn_inputproduct;
    private javax.swing.JButton btn_logout;
    private javax.swing.JButton btn_refreshProduct;
    private javax.swing.JButton btn_refreshTransaction;
    private javax.swing.JButton btn_reset;
    private javax.swing.JButton btn_save;
    private javax.swing.JButton btn_searchidProduct;
    private javax.swing.JButton btn_searchidTransaction;
    private javax.swing.JButton btn_searchnameProduct;
    private javax.swing.JButton btn_searchnameTransaction;
    private javax.swing.JButton btn_updatetrans;
    private org.jdesktop.swingx.JXDatePicker dp_date;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel label_id;
    private javax.swing.JLabel label_idtitle;
    private javax.swing.JLabel label_name;
    private javax.swing.JSpinner spn_totalorder;
    private javax.swing.JTable tb_product;
    private javax.swing.JTable tb_transaction;
    private javax.swing.JTextField tf_Total;
    private javax.swing.JTextField tf_customer;
    private javax.swing.JTextField tf_findProduct;
    private javax.swing.JTextField tf_findTransaction;
    private javax.swing.JTextField tf_id;
    private javax.swing.JTextField tf_merk;
    private javax.swing.JTextField tf_price;
    private javax.swing.JTextField tf_series;
    private javax.swing.JTextField tf_stock;
    // End of variables declaration//GEN-END:variables
}
